### ISSUE TITLE
[Enhancement]: Update to 5.6.0

### ISSUE THREAD

**Issue by rubenwardy** [snapcrafters/minetest#16]
### What changes would you like?

5.4.1 is over a year old, the snap should be updated to the latest version

### Any extra information?

5.5.1 release news: https://forum.minetest.net/viewtopic.php?t=28131

This will require building with Minetest's Irrlicht fork. See https://github.com/snapcrafters/minetest/pull/14

**Comment by rubenwardy** [comment]
5.6.0 is now availalbe: https://blog.minetest.net/2022/08/04/5.6.0-released/

**Comment by galgalesh** [comment]
Thanks for reporting this, version 5.6.1 was released to stable now.
