### ISSUE TITLE
[Enhancement]: Minetest 5.8.0

### ISSUE THREAD

**Issue by SmallJoker** [snapcrafters/minetest#23]
### What changes would you like?

*Bonjour.*

https://dev.minetest.net/Changelog#5.7.0_.E2.86.92_5.8.0

IrlrichtMt13

**Comment by popey** [comment]
Sadly, it fails to build:

```
-- Found IrrlichtMt 1.9.0.10
CMake Error at CMakeLists.txt:148 (message):
  At least IrrlichtMt 1.9.0mt13 is required to build
```

Full log: https://launchpad.net/~build.snapcraft.io/+snap/0fbc1d1142be3edd01556d4ec3766968/+build/2317610
