### ISSUE TITLE
[Enhancement]: Minetest should no longer ship with Minetest Game

### ISSUE THREAD

**Issue by rubenwardy** [snapcrafters/minetest#25]
### What changes would you like?

Minetest is a game creation platform with many different games available. From 5.8.0, we no longer recommend shipping with Minetest Game so that the player can chose which game they want to play.

Without MTG, the user is directed to download a game from [ContentDB](https://content.minetest.net) if they wish to play singleplayer. They can continue to play multiplayer without downloading a game (as code is all server-side)

### Any extra information?

For more information, see: https://blog.minetest.net/2023/12/04/5.8.0-released/#minetest-no-longer-ships-with-a-default-game

**Comment by popey** [comment]
Thanks for the issue @rubenwardy - apologies for not getting back to it sooner. 
So as I understand it we should be able to simply nuke the entire [minetestgame ](https://github.com/snapcrafters/minetest/blob/master/snap/snapcraft.yaml#L55 )stanza, and minetest should work as expected by the upstream project?

**Comment by rubenwardy** [comment]
That's correct
